# Generated by Django 2.1.3 on 2018-12-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_post_courses_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='courses_contact',
            field=models.EmailField(blank=True, default='user@example.com', max_length=70, null=True, unique=True),
        ),
    ]
