# Generated by Django 2.1.3 on 2018-12-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_post_courses_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='courses_contact',
        ),
    ]
