# Generated by Django 2.1.3 on 2018-12-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_post_courses_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default='$20/week', max_length=50),
        ),
    ]
