# Generated by Django 2.1.3 on 2018-12-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_post_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='schedule',
            field=models.TextField(blank=True, default='Monday: 5:30-6:30\n\t\tTuesday: 6:30-7:30'),
        ),
    ]
