# Generated by Django 2.1.3 on 2018-12-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='city',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
    ]
