# Generated by Django 2.1.3 on 2018-12-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20181229_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.TextField(default='post.author.email'),
        ),
    ]
