# Generated by Django 2.1.3 on 2018-12-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_post_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contact',
            field=models.TextField(default='123@exampleme.com'),
        ),
    ]
