# Generated by Django 2.1.3 on 2018-12-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20181229_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contact',
        ),
    ]
