# Generated by Django 2.1.3 on 2018-12-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_post_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='courses_image',
        ),
    ]
