# Generated by Django 2.1.3 on 2018-12-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20181229_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
