# Generated by Django 2.1.3 on 2018-12-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20181230_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='schedule',
            field=models.TextField(blank=True, default='Monday: 5:30-6:30\n\tTuesday: 6:30-7:30'),
        ),
    ]
