# Generated by Django 2.1.3 on 2019-01-03 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_auto_20190102_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image1',
        ),
    ]
