# Generated by Django 2.1.3 on 2019-01-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_post_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
