# Generated by Django 2.1.3 on 2019-01-03 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20190102_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image1',
            new_name='mainImage',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image2',
            new_name='subImage1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image3',
            new_name='subImage2',
        ),
    ]
