# Generated by Django 2.1.3 on 2019-01-03 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_auto_20190102_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sub_Image1',
            new_name='sub_Image_1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='sub_Image2',
            new_name='sub_Image_2',
        ),
    ]
